MODEL:
  TYPE: focalnet_large_fl3
  NAME: focalnet_large_fl3
  DROP_PATH_RATE: 0.5
  FOCAL:
    EMBED_DIM: 192
    FOCAL_LEVELS: [3, 3, 3, 3]
    FOCAL_WINDOWS: [5, 5, 5, 5]
    USE_CONV_EMBED: True
    USE_POSTLN: True
    USE_LAYERSCALE: True