MODEL:
  TYPE: focalnet_xlarge_fl4
  NAME: focalnet_xlarge_fl4
  DROP_PATH_RATE: 0.5
  FOCAL:
    EMBED_DIM: 256
    DEPTHS: [2, 2, 18, 2]
    FOCAL_LEVELS: [4, 4, 4, 4]
    FOCAL_WINDOWS: [3, 3, 3, 3]
    USE_CONV_EMBED: True
    USE_POSTLN: True
    USE_LAYERSCALE: True