MODEL:
  TYPE: focalnet_huge_fl3
  NAME: focalnet_huge_fl3
  DROP_PATH_RATE: 0.5
  FOCAL:
    EMBED_DIM: 352
    DEPTHS: [2, 2, 18, 2]
    FOCAL_LEVELS: [3, 3, 3, 3]
    FOCAL_WINDOWS: [3, 3, 3, 3]
    USE_CONV_EMBED: True
    USE_POSTLN: True
    USE_LAYERSCALE: True
    USE_POSTLN_IN_MODULATION: True