model_name: "LUCF_Net"
root_path: "/amax/home/Admin/work/paper_code/LUCF-Net-main/data/ACDC"
volume_path: "/amax/home/Admin/work/paper_code/LUCF-Net-main/data/ACDC/test"
dataset: "ACDC"
list_dir: "/amax/home/Admin/work/paper_code/LUCF-Net-main/data/ACDC/lists_ACDC"
num_classes: 4
in_chans: 1
max_iterations: 30000
max_epochs: 300
batch_size: 24
output_dir: "model_pth/ACDC"
is_pretrained: false
pretrained_pth: ""
n_gpu: 1
gpu: "2"
deterministic: 1
base_lr: 0.05
save_interval: 20
img_size: 224
seed: 2222
n_skip: 3
z_spacing: 10
exp: "1"
