model_name: "LUCF_Net"
root_path: "../data/AMOS/amos_2d/train_npz_new"
volume_path: "../data/synapse/amos_2d/test_vol_h5_new"
dataset: "Synapse"
list_dir: "../data/synapse/amos_2d/lists_amos"
num_classes: 14
in_chans: 1
max_iterations: 30000
max_epochs: 600
batch_size: 16
output_dir: "model_pth/AMOS"
is_pretrained: false
pretrained_pth: ""
n_gpu: 1
gpu: "1"
deterministic: 1
base_lr: 0.05
save_interval: 20
img_size: 224
seed: 2222
n_skip: 3
z_spacing: 1
exp: "1"
