model_name: "LUCF_Net"
root_path: "/amax/home/Admin/work/paper_code/LUCF-Net-main/data/Flare21_272/train_npz_new"
volume_path: "/amax/home/Admin/work/paper_code/LUCF-Net-main/data/Flare21_272/test_vol_h5_new"
dataset: "Flare21"
list_dir: "/amax/home/Admin/work/paper_code/LUCF-Net-main/data/Flare21_272/lists_Flare"
num_classes: 5
in_chans: 1
max_iterations: 30000
max_epochs: 300
batch_size: 16
workers: 2
output_dir: "model_pth/FLARE21"
is_pretrained: false
pretrained_pth: ""
n_gpu: 1
gpu: "0"
deterministic: 1
base_lr: 0.05
save_interval: 20
img_size: 224
seed: 2222
n_skip: 3
z_spacing: 1
exp: "1"
