model_name: "LUCF_Net"
root_path: "/amax/home/Admin/work/paper_code/LUCF-Net-main/data/skin_lesion/isic2016_jpg_512_smooth"
volume_path: ""
dataset: "ISIC"
list_dir: ""
num_classes: 1
in_chans: 3
max_iterations: 30000
max_epochs: 200
batch_size: 4
output_dir: "model_pth/ISIC"
is_pretrained: false
pretrained_pth: ""
n_gpu: 1
gpu: "3"
deterministic: 1
base_lr: 0.025
save_interval: 20
img_size: 224
seed: 2222
n_skip: 3
z_spacing: 1
exp: "1"
